{% set name = "opentelemetry-exporter-otlp-proto-http" %}
{% set version = "1.34.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/opentelemetry_exporter_otlp_proto_http-{{ version }}.tar.gz
  sha256: 3f674dbc32549a2fae413a77428d59b38e8c8b4caaf7f594ae2c2f8d2f018014

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - hatchling
    - pip
  run:
    - typing_extensions >=4.5.0
    - python >={{ python_min }}
    - deprecated >=1.2.6
    - googleapis-common-protos >=1.52,<2.dev0
    - opentelemetry-api >=1.15,<2.dev0
    - opentelemetry-proto ==1.34.0
    - opentelemetry-sdk >=1.34.0,<1.35.dev0
    - opentelemetry-exporter-otlp-proto-common ==1.34.0
    - requests >=2.7,<3.dev0
  # NOTE backoff only required for py<37 but pip checks fails without it
    #- backoff >=1.10.0,<3.0.0
    # - responses ==0.22.0
    # - typing_extensions >=4.5.0

test:
  imports:
    - opentelemetry
    - opentelemetry.exporter
    - opentelemetry.exporter.otlp.proto.http
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/open-telemetry/opentelemetry-python/tree/main/exporter/opentelemetry-exporter-otlp-proto-http
  summary: OpenTelemetry Collector Protobuf over HTTP Exporter
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - rxm7706
    - mariusvniekerk
    - conda-forge/opentelemetry-api
    - conda-forge/opentelemetry-proto
    - conda-forge/opentelemetry-sdk
    - conda-forge/opentelemetry-exporter-otlp-proto-common
