{% set name = "opentelemetry-exporter-otlp-proto-http" %}
{% set version = "1.29.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/opentelemetry_exporter_otlp_proto_http-{{ version }}.tar.gz
  sha256: b10d174e3189716f49d386d66361fbcf6f2b9ad81e05404acdee3f65c8214204

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.8
    - hatchling
    - pip
  run:
    - python >=3.8
    - deprecated >=1.2.6
    - googleapis-common-protos ~=1.52
    - opentelemetry-api ~=1.15
    - opentelemetry-proto ==1.29.0
    - opentelemetry-sdk ~=1.29.0
    - opentelemetry-exporter-otlp-proto-common ==1.29.0
    - requests ~=2.7
  # NOTE backoff only required for py<37 but pip checks fails without it
    #- backoff >=1.10.0,<3.0.0
    # - responses ==0.22.0

test:
  imports:
    - opentelemetry
    - opentelemetry.exporter
    - opentelemetry.exporter.otlp.proto.http
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/open-telemetry/opentelemetry-python/tree/main/exporter/opentelemetry-exporter-otlp-proto-http
  summary: OpenTelemetry Collector Protobuf over HTTP Exporter
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - rxm7706
    - mariusvniekerk
    - conda-forge/opentelemetry-api
    - conda-forge/opentelemetry-proto
    - conda-forge/opentelemetry-sdk
    - conda-forge/opentelemetry-exporter-otlp-proto-common
